fix: fix random open stream fail
nervosnetwork/tentacle pull request #298
Opened 2021-01-21 05:28 UTC by driftluo

fix #297

2021-01-21 08:40 UTC, quake commented
need a unit test to prevent regressions

2021-01-21 08:47 UTC, driftluo commented
> need a unit test to prevent regressions

The modified code cannot construct such a test, but before the modification, can do it

2021-01-21 09:03 UTC, TheWaWaR commented on yamux/src/stream.rs
> +        }
Handle this logic in a function instead of copying the code.

2021-01-21 09:34 UTC, quake requested changes

2021-01-22 03:33 UTC, doitian commented
> > need a unit test to prevent regressions
> 
> The modified code cannot construct such a test, but before the modification, can do it

The regression test case means when the code changes back, the test case will fail.

2021-01-22 05:16 UTC, TheWaWaR approved these changes

2021-01-22 07:28 UTC, quake approved these changes

2021-01-22 07:34 UTC, merged