fix: Fix yamux close
nervosnetwork/tentacle pull request #309
Opened 2021-02-18 03:37 UTC by driftluo

1. fix remote does not respond go away
2. fix drop with local close should send event

2021-02-19 08:46 UTC, doitian commented
Could you provide more context about the related design, how to reproduce the problem and how it is fixed? It's really hard for reviewers to catch up this fixing without understanding the whole design of yamux.

2021-02-19 09:44 UTC, doitian requested changes
Suggest to add more details comments to explain how to close the session when the remote peer does not respond to our sent go away code.

2021-02-19 09:44 UTC, doitian commented on yamux/src/stream.rs
> +                let _ignore = self.unbound_event_sender.unbounded_send(event);
Some comments can be added here to explain why `rst_event` is not required when `LocalClosing`.

2021-02-19 09:44 UTC, doitian commented on yamux/src/session.rs
> +            while let Some(Ok(mut stream)) = session.next().await {
Since this test has no assertions, it's better to add some comments about what's expected here.

2021-02-19 09:44 UTC, doitian commented on yamux/src/session.rs
> +        // max wait time for remote go away
```suggestion
        // Reuse the keealive timer to set a time out. If remote peer does not respond within the time out, consider this session as remote gone away.
        // See how `self.keepalive` is polled for details.
```

2021-02-19 09:44 UTC, doitian commented on yamux/src/session.rs
> +                        // deadline for local go away wait time
```suggestion
                        // The remote peer has not responded to our sent go away code. Assume that remote peer has gone away and this session should be closed.
```

2021-02-19 10:47 UTC, TheWaWaR approved these changes

2021-02-22 09:13 UTC, doitian approved these changes

2021-02-22 09:15 UTC, merged